# Generated by Django 4.1 on 2024-02-14 17:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question_title', models.CharField(max_length=450)),
                ('status', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=999)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.CharField(blank=True, default='', max_length=150)),
                ('teliphone', models.CharField(blank=True, default='', max_length=150)),
                ('contact_info', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=150)),
                ('facebook', models.CharField(blank=True, default='', max_length=150)),
                ('twitter', models.CharField(blank=True, default='', max_length=150)),
                ('youtube', models.CharField(blank=True, default='', max_length=150)),
                ('site_icon', models.ImageField(blank=True, null=True, upload_to='site/images')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/images')),
                ('site_title', models.CharField(blank=True, default='', max_length=150)),
                ('site_name', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Testonomial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=150)),
                ('content', models.TextField(blank=True, default='')),
                ('page_type', models.CharField(choices=[('normal', 'Normal'), ('navbar_page', 'Navbar Page'), ('footer_page', 'Footer Page')], max_length=20)),
                ('first_images', models.ImageField(blank=True, null=True, upload_to='testonomial/images')),
                ('second_images', models.ImageField(blank=True, null=True, upload_to='testonomial/images')),
                ('place', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionHaveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('answer_title', models.CharField(max_length=450)),
                ('status', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='managements.question')),
            ],
        ),
    ]
