# Generated by Django 4.1 on 2024-02-14 17:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=450)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=450, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='holiday/images/')),
                ('important_points', models.CharField(max_length=450)),
                ('trekking_difficulty', models.CharField(max_length=450)),
                ('stay_type', models.CharField(max_length=450)),
                ('activities', models.CharField(max_length=450)),
                ('duration_stay', models.IntegerField()),
                ('description', models.TextField()),
                ('map', models.URLField(blank=True, null=True)),
                ('trip_information', models.CharField(max_length=450)),
                ('ltinerary', models.CharField(max_length=450)),
                ('weather', models.CharField(max_length=450)),
                ('equipment', models.CharField(max_length=450)),
                ('useful_information', models.CharField(max_length=450)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=400, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='holiday/holiday_type_image/')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayTripReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=1, help_text='Enter a number less than 5 stars', validators=[django.core.validators.MaxValueValidator(5)])),
                ('comments', models.CharField(max_length=2000)),
                ('holiday_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='holiday.holidaytrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayTripHaveImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='holiday/images/')),
                ('holiday_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='holiday.holidaytrip')),
            ],
        ),
    ]
