# Generated by Django 4.1 on 2024-02-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_holidaytrip_holiday_tyoe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidaytrip',
            old_name='holiday_tyoe',
            new_name='holiday_type',
        ),
    ]
